/**
 * Single source of truth for all valid hypothesis_type values.
 *
 * Rules:
 *  - PRECISION_PASS_TYPES is what the app *generates* today.
 *  - LEGACY_COMPAT_TYPES covers old generic names stored in existing DB rows.
 *  - ALL_HYPOTHESIS_TYPES is the full union and must match the DB check constraint.
 *  - DB_CHECK_CONSTRAINT_VALUES is the exact string you can paste into a migration
 *    if the constraint needs updating.
 */

/** New specific types generated by generateHypotheses() */
export const PRECISION_PASS_TYPES = [
  'noop',
  'scale_up',
  'scale_down',
  'spread_expand',
  'spread_reduce',
  'beam_extend',
  'beam_reduce',
  'tine_extend',
  'tine_reduce',
  'mass_boost',
  'mass_reduce',
  'symmetry_beam',
  'symmetry_tine',
  'deduction_reduce',
  'deduction_increase',
  'swap_sides',
  'combo',
] as const

/** Legacy generic types kept for backwards compat with stored rows */
export const LEGACY_COMPAT_TYPES = [
  'scale',
  'spread',
  'beam',
  'tine',
  'mass',
  'deduction',
] as const

export const ALL_HYPOTHESIS_TYPES = [
  ...PRECISION_PASS_TYPES,
  ...LEGACY_COMPAT_TYPES,
] as const

export type HypothesisTypeValue = (typeof ALL_HYPOTHESIS_TYPES)[number]

/**
 * Validate a hypothesis type value against the allowed set.
 * Returns false if the value would violate the DB check constraint.
 */
export function isValidHypothesisType(value: string): value is HypothesisTypeValue {
  return (ALL_HYPOTHESIS_TYPES as readonly string[]).includes(value)
}

/**
 * Validate an array of hypothesis type values and return any invalid ones.
 * Use this before inserting candidates to produce an actionable error message.
 */
export function findInvalidHypothesisTypes(values: string[]): string[] {
  return values.filter(v => !isValidHypothesisType(v))
}

/**
 * The exact SQL VALUES list for the hypothesis_candidates_hypothesis_type_check constraint.
 * Run the migration below if the DB check constraint is out of date.
 *
 * ALTER TABLE hypothesis_candidates
 *   DROP CONSTRAINT IF EXISTS hypothesis_candidates_hypothesis_type_check,
 *   ADD CONSTRAINT hypothesis_candidates_hypothesis_type_check
 *     CHECK (hypothesis_type = ANY(ARRAY[
 *       'noop','scale_up','scale_down','spread_expand','spread_reduce',
 *       'beam_extend','beam_reduce','tine_extend','tine_reduce',
 *       'mass_boost','mass_reduce','symmetry_beam','symmetry_tine',
 *       'deduction_reduce','deduction_increase','swap_sides','combo',
 *       'scale','spread','beam','tine','mass','deduction'
 *     ]::text[]));
 */
export const DB_CHECK_CONSTRAINT_VALUES = ALL_HYPOTHESIS_TYPES.join("','")
